### ISSUE TITLE
Dynamics Layout Not Working

### ISSUE THREAD

**Issue by david-macias** [CiscoDevNet/webex-contact-center-widget-starter#71]
**Describe the bug**
After going through the instructions in detailed I'm still not able to see the CRM inside WxCC desktop or see WxCC inside Dynamics.

**To Reproduce**
1. Made all changes described in this article (https://help.webex.com/en-us/article/aw26j2/Integrate-Webex-Contact-Center-with-Microsoft-Dynamics-365#Cisco_Reference.dita_64af8d5d-33da-4c4e-b03e-45bbbc4a291d).
2. Make the requested changes in the layout found in Github.
3. Login to either Dynamics or WxCC.

**Expected behavior**
Expect to see the CRM inside WxCC or see WxCC desktop inside CRM.

**Desktop (please complete the following information):**
- N/A

**Comment by arubhatt** [comment]
Hello David, could you please confirm that the issue is present in the latest widget layout - we moved our layouts here and updated the latest version - https://github.com/CiscoDevNet/webex-contact-center-crm-integrations/tree/main/MS%20Dynamics

Please let us know so we can close out this issue.

Thanks,
